trigger:
- master

pr:
- master  

jobs:

- job: build_and_test
  displayName:  'Test using '
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      pip-gcc8:
        gccVersion: '8'
        DEVITO_OPENMP: '0'
        MPI_INSTALL: '1'
        installWithPip: 'true'
        DEVITO_BACKEND: 'core'
        RUN_EXAMPLES: 'false'
      conda-gcc8:
        gccVersion: '8'
        DEVITO_OPENMP: '0'
        MPI_INSTALL: '1'
        installWithPip: 'false'
        DEVITO_BACKEND: 'core'
        RUN_EXAMPLES: 'true'
      conda-gcc9:
        gccVersion: '9'
        DEVITO_OPENMP: '0'
        MPI_INSTALL: '1'
        installWithPip: 'false'
        DEVITO_BACKEND: 'core'
        RUN_EXAMPLES: 'true'
      openmp-conda-gcc8:
        gccVersion: '8'
        DEVITO_OPENMP: '1'
        MPI_INSTALL: '1'
        installWithPip: 'false'
        DEVITO_BACKEND: 'core'
        RUN_EXAMPLES: 'true'
      nompi-conda-gcc5:
        gccVersion: '5'
        DEVITO_OPENMP: '0'
        MPI_INSTALL: '0'
        installWithPip: 'false'
        DEVITO_BACKEND: 'core'
        RUN_EXAMPLES: 'false'
      ops-conda-gcc7:
        gccVersion: '7'
        DEVITO_OPENMP: '0'
        MPI_INSTALL: '1'
        installWithPip: 'false'
        DEVITO_BACKEND: 'ops'
        RUN_EXAMPLES: 'false'
      yask-conda-gcc7:
        gccVersion: '7'
        DEVITO_OPENMP: '0'
        MPI_INSTALL: '1'
        installWithPip: 'false'
        DEVITO_BACKEND: 'yask'
        RUN_EXAMPLES: 'false'

  timeoutInMinutes: 120
  steps:
  - task: Docker@1
    displayName: "Build container"
    inputs:
      command: 'build'
      dockerFile: Dockerfile.pipelines
      arguments:
        --build-arg gccVersion=$(gccVersion)
        --build-arg installWithPip=$(installWithPip)
        --build-arg DEVITO_BACKEND=$(DEVITO_BACKEND)
        --build-arg DEVITO_OPENMP=$(DEVITO_OPENMP)
        --build-arg MPI_INSTALL=$(MPI_INSTALL)
        --build-arg RUN_EXAMPLES=$(RUN_EXAMPLES)
  - task: Docker@1
    displayName: "Run tests"
    inputs:
      command: 'run'
      runInBackground: false
