version: '2'

services:
  devito:
    build:
      context: .
      dockerfile: docker/Dockerfile.devito
    volumes:
      - ./devito:/app/devito/devito
      - ./tests:/app/devito/tests
      - ./examples:/app/devito/examples
    ports:
      - 8888:8888

  devito.nvidia:
    build:
      context: .
      dockerfile: docker/Dockerfile.devito
      args:
        base: devitocodes/bases:nvidia-nvc
    volumes:
      - ./devito:/app/devito/devito
      - ./tests:/app/devito/tests
      - ./examples:/app/devito/examples
    ports:
      - 8888:8888
    runtime: nvidia
