name: devito
channels:
  - defaults
dependencies:
  - numpy >=1.11
  - sympy ==1.0
  - matplotlib
  - pytest
  - flake8>=2.1.0
  - cached-property
  - psutil>=5.1.0
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - "git+git://github.com/inducer/cgen"
    - "git+git://github.com/inducer/codepy"
    - pytest-ipynb >=1.1
    - py-cpuinfo
