name: devito
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - numpy>=1.14
  - sympy>=1.4
  - cgen
  - scipy
  - matplotlib
  - pytest
  - flake8>=2.1.0
  - parso>=0.1.0
  - nbval
  - cached-property
  - psutil>=5.1.0
  - sphinx
  - sphinx_rtd_theme
  - distributed>=1.27
  - cython
  - click
  - codecov
  - pytest-cov
  - multidict
  - frozendict
  - nb_conda_kernels
  - pip
  - pip:
    - "git+https://github.com/inducer/codepy"
    - pyzfp~=0.2rc4
    - pyrevolve~=2.1.3rc4
    - py-cpuinfo
    - anytree>=2.4.3
