name: devito
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - numpy>=1.11
  - sympy==1.1
  - cgen
  - scipy
  - matplotlib
  - pytest
  - flake8>=2.1.0
  - parso==0.1.0
  - nbval
  - cached-property
  - psutil>=5.1.0
  - sphinx
  - sphinx_rtd_theme
  - dask
  - distributed
  - scikit-image
  - cython
  - click
  - codecov
  - pytest-cov
  - multidict
  - frozendict
  - pip:
    - "git+https://github.com/inducer/codepy"
    - "git+https://github.com/opesci/pyrevolve"
    - py-cpuinfo
