name: devito
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - numpy==1.14
  - sympy==1.2
  - cgen
  - scipy
  - mpi4py
  - matplotlib
  - pytest
  - flake8>=2.1.0
  - parso>=0.1.0
  - nbval
  - cached-property
  - psutil>=5.1.0
  - sphinx
  - sphinx_rtd_theme
  - dask==0.18.1
  - distributed==1.22.0
  - scikit-image
  - cython
  - click
  - codecov
  - pytest-cov
  - multidict
  - frozendict
  - pip:
    - "git+https://github.com/inducer/codepy"
    - "git+https://github.com/opesci/pyrevolve"
    - py-cpuinfo
    - anytree>=2.4.3
