name: Publish docker image

on:
  release:
    types: [published]
  push:
    branches:
      - master         # Push events on master branch

jobs:
  deploy-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout devito
        uses: actions/checkout@v1

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: CPU image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: devitocodes/devito
          dockerfile: ./docker/Dockerfile
          tags: cpu-dev

      - name: CPU image release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: devitocodes/devito
          dockerfile: ./docker/Dockerfile
          tags: cpu-latest,'cpu-${{ github.event.release.tag_name }}'

      - name: GPU image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: devitocodes/devito
          dockerfile: ./docker/Dockerfile.nvidia
          tags: gpu-dev

      - name: GPU image release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: devitocodes/devito
          dockerfile: ./docker/Dockerfile.nvidia
          tags: gpu-latest,'gpu-${{ github.event.release.tag_name }}'

  # Comment out 'cpu-latest' until next release
  test-cpu-image:
    needs: deploy-docker
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        #im-name: [cpu-dev, cpu-latest]
        im-name: [cpu-dev]

    steps:
        - name: Run simple test
          run: |
             docker pull 'devitocodes/devito:${{ matrix.im-name }}'
             docker run --rm --name testrun 'devitocodes/devito:${{ matrix.im-name }}' pytest tests/test_operator.py

  # Comment out until gpu docker image problem resolved
  test-gpu-image:
    needs: deploy-docker
    runs-on: [self-hosted, gpu]

    strategy:
      fail-fast: false
      matrix:
        im-name: [gpu-dev, gpu-latest]

    steps:
        - name: Run simple test
          run: |
             docker pull 'devitocodes/devito:${{ matrix.im-name }}'
             docker run --gpus --rm --name testrun 'devitocodes/devito:${{ matrix.im-name }}' pytest tests/test_gpu_openacc.py
