name: Publish docker image

on:
  release:
    types: [published]
  push:
    branches:
      - master         # Push events on master branch

jobs:
  deploy-docker-cpu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout devito
        uses: actions/checkout@v2

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: CPU image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: devitocodes/devito:cpu-dev

      - name: CPU image release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            devitocodes/devito:cpu-latest
            devitocodes/devito:cpu-${{ github.event.release.tag_name }}

  deploy-docker-gpu:
    runs-on: [self-hosted, gpu, docker]

    steps:
      - name: Checkout devito
        uses: actions/checkout@v2

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GPU image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./docker/Dockerfile.nvidia
          push: true
          network: host
          tags: devitocodes/devito:gpu-dev

      - name: GPU image release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./docker/Dockerfile.nvidia
          push: true
          network: host
          tags: |
            devitocodes/devito:gpu-latest
            devitocodes/devito:gpu-${{ github.event.release.tag_name }}

  deploy-docker-intel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout devito
        uses: actions/checkout@v2

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: CPU Intel image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./docker/Dockerfile.intel
          push: true
          network: host
          tags: devitocodes/devito:cpu-intel-dev

      - name: CPU intel image release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./docker/Dockerfile.intel
          push: true
          network: host
          tags: |
            devitocodes/devito:cpu-intel-latest
            devitocodes/devito:cpu-${{ github.event.release.tag_name }}

  # Comment out 'cpu-latest' until next release
  test-cpu-image:
    needs: deploy-docker-cpu
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        #im-name: [cpu-dev, cpu-latest]
        im-name: [cpu-dev]

    steps:
        - name: Run simple test
          run: |
             docker pull 'devitocodes/devito:${{ matrix.im-name }}'
             docker run --rm --name testrun 'devitocodes/devito:${{ matrix.im-name }}' pytest tests/test_operator.py

  test-gpu-image:
    needs: deploy-docker-gpu
    runs-on: [self-hosted, gpu, docker]

    strategy:
      fail-fast: false
      matrix:
        #im-name: [gpu-dev, gpu-latest]
        im-name: [gpu-dev]

    steps:
        - name: Run simple test
          run: |
             docker pull 'devitocodes/devito:${{ matrix.im-name }}'
             docker run --gpus all --rm --name testrun 'devitocodes/devito:${{ matrix.im-name }}' pytest tests/test_gpu_openacc.py

        # NOTE: Suitable for the time being but will need to modify when we switch runners
        - name: Clean
          run: |
            docker system prune -a -f

  test-cpu-intel-image:
    needs: deploy-docker-cpu-intel
    runs-on: [self-hosted, gpu, docker]

    strategy:
      fail-fast: false
      matrix:
        #im-name: [gpu-dev, gpu-latest]
        im-name: [cpu-intel-dev]

    steps:
        - name: Run simple test
          run: |
             docker pull 'devitocodes/devito:${{ matrix.im-name }}'
             docker run --rm --name testrun 'devitocodes/devito:${{ matrix.im-name }}' pytest tests/test_operator.py

        # NOTE: Suitable for the time being but will need to modify when we switch runners
        - name: Clean
          run: |
            docker system prune -a -f